language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
env:
  - DB=postgres ORM=active_record RAILS_VERSION=5.1
  - DB=mysql ORM=active_record RAILS_VERSION=5.1
  - DB=postgres ORM=active_record RAILS_VERSION=5.2
  - DB=mysql ORM=active_record RAILS_VERSION=5.2
  - DB=postgres ORM=active_record RAILS_VERSION=6.0
  - DB=mysql ORM=active_record RAILS_VERSION=6.0
  - DB=postgres ORM=sequel SEQUEL_VERSION=5
  - DB=mysql ORM=sequel SEQUEL_VERSION=5
  - DB=sqlite3 ORM=sequel SEQUEL_VERSION=5
  - DB=sqlite3 ORM= TEST_PERFORMANCE=true
  - DB=sqlite3 ORM= I18N_FALLBACKS=true
matrix:
  fast_finish: true

before_script:
  - bundle exec rake db:create db:up
before_install: gem install bundler
addons:
  postgresql: "9.4"
  apt:
    update: true
services:
  - postgresql
  - mysql
